name: Linting, Testing, Building

on:
  pull_request:
    branches: [main, development]

  push:
    branches: [main]

  workflow_dispatch:

env:
  PORT: 3000 # workflow level environment variable

jobs:
  Linting:
    # env: # job level environment variable
    #   PORT: 3000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Linting Rules
        run: npm run lint

  Testing:
    needs: Linting
    environment: TEST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Unit Tests
        run: npm run test

      - name: Run e2e Tests
        run: npm run test:e2e

  Building:
    needs: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Build
        run: npm run build