name: node-jest-typescript-starter

on:
  pull_request:
    # branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Linting Rules
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Run Integration Tests
        run: npm run test:e2e