name: node-jest-typescript-starter

on:
  pull_request:
    # branches: [master]
  push:
    branches: [main]

env:
  PORT: 3000 # workflow level environment variable

jobs:
  pipeline:
    env: # job level environment variable
      PORT: 3000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Linting Rules
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Run Integration Tests
        run: npm run test:e2e
      
      - name: output env
        run: |
          echo $PORT
          echo ${{ env.PORT }}
          "echo ${{ secrets.USERNAME }}-test"