name: Linting, Testing, Building

on:
  pull_request:
    branches: [main, development]

  workflow_dispatch:

env:
  PORT: 3000 # workflow level environment variable example

jobs:
  Linting:
    # env: # job level environment variable
    #   PORT: 3000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Linting Rules
        run: npm run lint

  Testing:
    needs: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Unit Tests
        run: npm run test

      - name: Run e2e Tests
        run: npm run test:e2e

  Danger-Review:
    needs: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Set up Git and run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_CI_TOKEN }}
        run: |
          git config --global user.name 'danger_ci_bot'
          git config --global user.email 'demirtasdurmus@gmail.com'
          npm run danger:ci
  
  # This job simulates a deployment to a staging environment
  Building:
    needs: Danger-Review
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Build
        run: npm run build