name: Releasing Workflow With Semantic Release

on:
  push:
    branches: [main, release/*]

jobs:
  Releasing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: display github object
        run: |
          echo ${{ toJson(github) }}

      - name: Set up Git and run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: |
          git config --global user.name 'semantic_release_bot'
          git config --global user.email 'demirtasdurmus@gmail.com'
          npx semantic-release

          # Get the current branch name
          current_branch=$(git rev-parse --abbrev-ref HEAD)

          # If the current branch is main, pull changes and rebase development
          if [ "$current_branch" = "main" ]; then
            git pull origin main
            git checkout development
            git rebase main
            git push origin development
          fi